name: dotnet pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Restore, build, and test for Api project
    - name: Restore dependencies for Api
      run: dotnet restore Api/Api.csproj

    - name: Build Api project
      run: dotnet build Api/Api.csproj --no-restore

    - name: Test Api project
      run: dotnet test Api/Api.csproj --no-build --verbosity normal

    # Restore, build, and test for Client project
    - name: Restore dependencies for Client
      run: dotnet restore Client/Client.csproj

    - name: Build Client project
      run: dotnet build Client/Client.csproj --no-restore

    - name: Test Client project
      run: dotnet test Client/Client.csproj --no-build --verbosity normal
